name: utility_scripts
channels:
 - conda-forge
 - bioconda
 - r
dependencies:
 - r-devtools
 - bioconductor-variantannotation
 - bioconductor-structuralvariantannotation
 - bioconductor-summarizedexperiment
 - bioconductor-biocgenerics
 - bioconductor-genomeinfodb
 - bioconductor-bsgenome
 - bioconductor-genomicranges
 - bioconductor-iranges
 - r-getopt
 - r-stringr
