# From here: https://github.com/reviewdog/action-misspell
name: reviewdog misspell
on: [pull_request]
jobs:
  misspell:
    name: runner / misspell
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v2.3.4
      - name: misspell
        uses: reviewdog/action-misspell@v1.11
        with:
          github_token: ${{ secrets.github_token }}
          locale: "UK"
          reporter: github-pr-review # Available:  github-pr-review adds comments in PR conversation
          level: error
          exclude: "*.css"